import { Suministro, ResumenAlimentador } from "./types";

export const CORTE_CRITICA = 96;

export const resumenAlimentador: ResumenAlimentador = {
  "alimentador": "ALIM_311",
  "suministros": 14951,
  "transformadores": 95,
  "zonas": 29,
  "llaves": 7,
  "tarifa": "BT5 B",
  "inspeccionar": 96,
  "transformadores_con_alerta": 50,
  "recupero_soles": 431477.8298037709
};

export const mockData: Suministro[] = [
  {
    "suministro": "SUM_007851",
    "sed": "SED_1538",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.916,
    "nivel_sospecha": "CRÍTICO",
    "recupero_soles": 4640.89,
    "score_prioridad": 4248.77,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados y registra un promedio de 5,239 kWh al mes. Su consumo cayó 96% entre el inicio y el final del año, sin recuperarse. Cayó 96%, muy por encima del 23% que cayó el resto de su subestación. Registra 551 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_001565",
    "sed": "SED_1538",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.583,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 7268.03,
    "score_prioridad": 4235.17,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 5.1 kW contratados. Venía registrando unos 29 kWh al mes y desde junio marca cero: lleva 7 meses seguidos sin registrar consumo. Cayó 100%, muy por encima del 24% que cayó el resto de su subestación. Mientras estuvo activo registraba más energía que el resto de su subestación, así que el corte a cero no cuadra con un local que simplemente dejó de operar. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_011487",
    "sed": "SED_0515",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.553,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 7152.97,
    "score_prioridad": 3958.09,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados. Venía registrando unos 18 kWh al mes y desde setiembre marca cero: lleva 4 meses seguidos sin registrar consumo. Cayó 100%, muy por encima del 14% que cayó el resto de su subestación. Aun antes de apagarse ya registraba 40% menos que el promedio de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_009931",
    "sed": "SED_0515",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.553,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 7121.03,
    "score_prioridad": 3939.46,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados. Venía registrando unos 20 kWh al mes y desde setiembre marca cero: lleva 4 meses seguidos sin registrar consumo. Cayó 100%, muy por encima del 14% que cayó el resto de su subestación. Aun antes de apagarse ya registraba 24% menos que el promedio de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_005240",
    "sed": "SED_1019",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.676,
    "nivel_sospecha": "MUY ALTO",
    "recupero_soles": 5757.51,
    "score_prioridad": 3892.11,
    "incertidumbre_alta": true,
    "explicacion": "Tiene 5.1 kW contratados. Venía registrando unos 80 kWh al mes y desde noviembre marca cero: lleva 2 meses seguidos sin registrar consumo. Cayó 69%, muy por encima del 29% que cayó el resto de su subestación. Mientras estuvo activo registraba más energía que el resto de su subestación, así que el corte a cero no cuadra con un local que simplemente dejó de operar. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_002297",
    "sed": "SED_0974",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.942,
    "nivel_sospecha": "CRÍTICO",
    "recupero_soles": 4093.17,
    "score_prioridad": 3854.02,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados y registra un promedio de 2,454 kWh al mes. Su consumo subió 108% en el año, un salto que no corresponde a variación estacional. Registra 18 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_006050",
    "sed": "SED_0090",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.547,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 6992.87,
    "score_prioridad": 3828.07,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12.1 kW contratados. Venía registrando unos 16 kWh al mes y desde octubre marca cero: lleva 3 meses seguidos sin registrar consumo. Cayó 100%, muy por encima del 30% que cayó el resto de su subestación. Aun antes de apagarse ya registraba 90% menos que el promedio de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_019051",
    "sed": "SED_2738",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.553,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 6782.27,
    "score_prioridad": 3748.87,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados. Venía registrando unos 57 kWh al mes y desde agosto marca cero: lleva 5 meses seguidos sin registrar consumo. Cayó 100%, muy por encima del 15% que cayó el resto de su subestación. Aun antes de apagarse ya registraba 24% menos que el promedio de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_018243",
    "sed": "SED_1207",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.604,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 6105.2,
    "score_prioridad": 3684.63,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados. Venía registrando unos 58 kWh al mes y desde setiembre marca cero: lleva 4 meses seguidos sin registrar consumo. Mientras estuvo activo registraba más energía que el resto de su subestación, así que el corte a cero no cuadra con un local que simplemente dejó de operar. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_016339",
    "sed": "SED_2661",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.907,
    "nivel_sospecha": "CRÍTICO",
    "recupero_soles": 4026.99,
    "score_prioridad": 3653.84,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados y registra un promedio de 4,680 kWh al mes. Su consumo cayó 45% entre el inicio y el final del año, sin recuperarse. Registra 33 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_002580",
    "sed": "SED_0515",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.575,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 6261.42,
    "score_prioridad": 3597.29,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados. Venía registrando unos 68 kWh al mes y desde junio marca cero: lleva 7 meses seguidos sin registrar consumo. Cayó 100%, muy por encima del 14% que cayó el resto de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_009955",
    "sed": "SED_1207",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.558,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 6216.12,
    "score_prioridad": 3466.94,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados. Venía registrando unos 54 kWh al mes y desde octubre marca cero: lleva 3 meses seguidos sin registrar consumo. Cayó 100%, muy por encima del 13% que cayó el resto de su subestación. Mientras estuvo activo registraba más energía que el resto de su subestación, así que el corte a cero no cuadra con un local que simplemente dejó de operar. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_005743",
    "sed": "SED_1207",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.547,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 6328.88,
    "score_prioridad": 3464.19,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados. Venía registrando unos 14 kWh al mes y desde octubre marca cero: lleva 3 meses seguidos sin registrar consumo. Aun antes de apagarse ya registraba 37% menos que el promedio de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_011741",
    "sed": "SED_0035",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.897,
    "nivel_sospecha": "CRÍTICO",
    "recupero_soles": 3857.88,
    "score_prioridad": 3459.79,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados. Venía registrando unos 1,818 kWh al mes y desde octubre marca cero: lleva 3 meses seguidos sin registrar consumo. Cayó 100%, muy por encima del 15% que cayó el resto de su subestación. Mientras estuvo activo registraba más energía que el resto de su subestación, así que el corte a cero no cuadra con un local que simplemente dejó de operar. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_008448",
    "sed": "SED_0933",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.946,
    "nivel_sospecha": "CRÍTICO",
    "recupero_soles": 3641.69,
    "score_prioridad": 3443.41,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados y registra un promedio de 2,966 kWh al mes. Su consumo subió 71% en el año, un salto que no corresponde a variación estacional. Registra 27 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_006162",
    "sed": "SED_1019",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.539,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 6321.42,
    "score_prioridad": 3408.81,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados. Venía registrando unos 31 kWh al mes y desde noviembre marca cero: lleva 2 meses seguidos sin registrar consumo. Cayó 59%, muy por encima del 22% que cayó el resto de su subestación. Aun antes de apagarse ya registraba 47% menos que el promedio de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_004030",
    "sed": "SED_1137",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.532,
    "nivel_sospecha": "MODERADO",
    "recupero_soles": 6282.46,
    "score_prioridad": 3342.68,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados. Venía registrando unos 38 kWh al mes y desde noviembre marca cero: lleva 2 meses seguidos sin registrar consumo. Aun antes de apagarse ya registraba 28% menos que el promedio de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_009490",
    "sed": "SED_1538",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.567,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 5873.93,
    "score_prioridad": 3329.59,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados y registra un promedio de 22 kWh al mes. Su consumo cayó 95% entre el inicio y el final del año, sin recuperarse. Cayó 95%, muy por encima del 24% que cayó el resto de su subestación. Está pagando por 11.1 kW de capacidad pero usa menos del 1% de ella, algo poco habitual en un cliente que mantiene el servicio activo. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_000944",
    "sed": "SED_1942",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.897,
    "nivel_sospecha": "CRÍTICO",
    "recupero_soles": 3701.82,
    "score_prioridad": 3318.99,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados y registra un promedio de 1,968 kWh al mes. Cayó 34% mientras el resto de su subestación se mantuvo estable (-13%): la caída es de este suministro, no del sector. Registra 11 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_011374",
    "sed": "SED_1041",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.585,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 5580.55,
    "score_prioridad": 3264.0,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados. Venía registrando unos 41 kWh al mes y desde agosto marca cero: lleva 5 meses seguidos sin registrar consumo. Cayó 100%, muy por encima del 12% que cayó el resto de su subestación. Aun antes de apagarse ya registraba 68% menos que el promedio de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_009540",
    "sed": "SED_0938",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.651,
    "nivel_sospecha": "MUY ALTO",
    "recupero_soles": 5004.8,
    "score_prioridad": 3258.49,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados. Venía registrando unos 171 kWh al mes y desde setiembre marca cero: lleva 4 meses seguidos sin registrar consumo. Cayó 100%, muy por encima del 6% que cayó el resto de su subestación. Aun antes de apagarse ya registraba 29% menos que el promedio de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_000990",
    "sed": "SED_1041",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.941,
    "nivel_sospecha": "CRÍTICO",
    "recupero_soles": 3432.02,
    "score_prioridad": 3229.97,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados y registra un promedio de 2,344 kWh al mes. Registra 31 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_005907",
    "sed": "SED_2475",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.795,
    "nivel_sospecha": "MUY ALTO",
    "recupero_soles": 4043.32,
    "score_prioridad": 3213.07,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados y registra un promedio de 3,845 kWh al mes. Su consumo subió 76% en el año, un salto que no corresponde a variación estacional. Registra 53 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_005029",
    "sed": "SED_2154",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.533,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 6014.83,
    "score_prioridad": 3205.98,
    "incertidumbre_alta": true,
    "explicacion": "Tiene 12 kW contratados y registra un promedio de 38 kWh al mes. Está pagando por 12 kW de capacidad pero usa menos del 1% de ella, algo poco habitual en un cliente que mantiene el servicio activo. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_001109",
    "sed": "SED_2413",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.941,
    "nivel_sospecha": "CRÍTICO",
    "recupero_soles": 3396.53,
    "score_prioridad": 3196.22,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados y registra un promedio de 1,592 kWh al mes. Su consumo subió 200% en el año, un salto que no corresponde a variación estacional. Registra 29 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_014910",
    "sed": "SED_1207",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.573,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 5515.63,
    "score_prioridad": 3161.28,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 5.1 kW contratados. Venía registrando unos 19 kWh al mes y desde noviembre marca cero: lleva 2 meses seguidos sin registrar consumo. Cayó 94%, muy por encima del 11% que cayó el resto de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_004099",
    "sed": "SED_2195",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.936,
    "nivel_sospecha": "CRÍTICO",
    "recupero_soles": 3370.69,
    "score_prioridad": 3154.77,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados y registra un promedio de 2,837 kWh al mes. Su consumo subió 129% en el año, un salto que no corresponde a variación estacional. Registra 12 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_002895",
    "sed": "SED_0212",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.554,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 5629.06,
    "score_prioridad": 3120.15,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados. Venía registrando unos 49 kWh al mes y desde octubre marca cero: lleva 3 meses seguidos sin registrar consumo. Cayó 100%, muy por encima del 14% que cayó el resto de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_013499",
    "sed": "SED_0090",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.889,
    "nivel_sospecha": "CRÍTICO",
    "recupero_soles": 3447.27,
    "score_prioridad": 3065.2,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 8.1 kW contratados. Venía registrando unos 1,280 kWh al mes y desde octubre marca cero: lleva 3 meses seguidos sin registrar consumo. Cayó 100%, muy por encima del 25% que cayó el resto de su subestación. Mientras estuvo activo registraba más energía que el resto de su subestación, así que el corte a cero no cuadra con un local que simplemente dejó de operar. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_017150",
    "sed": "SED_1270",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.939,
    "nivel_sospecha": "CRÍTICO",
    "recupero_soles": 3257.66,
    "score_prioridad": 3059.28,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados y registra un promedio de 2,228 kWh al mes. Su consumo subió 200% en el año, un salto que no corresponde a variación estacional. Registra 20 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_018118",
    "sed": "SED_0515",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.907,
    "nivel_sospecha": "CRÍTICO",
    "recupero_soles": 3307.44,
    "score_prioridad": 2999.52,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados y registra un promedio de 442 kWh al mes. Solo registra consumo en 3 de los 12 meses del año. Registra 32 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_014340",
    "sed": "SED_2362",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.751,
    "nivel_sospecha": "MUY ALTO",
    "recupero_soles": 3974.74,
    "score_prioridad": 2986.63,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados y registra un promedio de 6,393 kWh al mes. Registra 55 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_017321",
    "sed": "SED_0035",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.551,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 5414.72,
    "score_prioridad": 2984.04,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados. Venía registrando unos 63 kWh al mes y desde octubre marca cero: lleva 3 meses seguidos sin registrar consumo. Cayó 100%, muy por encima del 16% que cayó el resto de su subestación. Aun antes de apagarse ya registraba 35% menos que el promedio de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_013724",
    "sed": "SED_2315",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.626,
    "nivel_sospecha": "MUY ALTO",
    "recupero_soles": 4690.41,
    "score_prioridad": 2937.37,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados. Venía registrando unos 148 kWh al mes y desde octubre marca cero: lleva 3 meses seguidos sin registrar consumo. Cayó 100%, muy por encima del 41% que cayó el resto de su subestación. Mientras estuvo activo registraba más energía que el resto de su subestación, así que el corte a cero no cuadra con un local que simplemente dejó de operar. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_011954",
    "sed": "SED_0933",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.568,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 5150.11,
    "score_prioridad": 2923.76,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados. Venía registrando unos 326 kWh al mes y desde setiembre marca cero: lleva 4 meses seguidos sin registrar consumo. Cayó 100%, muy por encima del 14% que cayó el resto de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_000731",
    "sed": "SED_2181",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.593,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4901.13,
    "score_prioridad": 2907.24,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados y registra un promedio de 20 kWh al mes. Su consumo cayó 97% entre el inicio y el final del año, sin recuperarse. Cayó 97%, muy por encima del 26% que cayó el resto de su subestación. Registra 250 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. Está pagando por 12 kW de capacidad pero usa menos del 1% de ella, algo poco habitual en un cliente que mantiene el servicio activo. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_000475",
    "sed": "SED_2362",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.874,
    "nivel_sospecha": "CRÍTICO",
    "recupero_soles": 3322.46,
    "score_prioridad": 2902.47,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados. Venía registrando unos 1,165 kWh al mes y desde octubre marca cero: lleva 3 meses seguidos sin registrar consumo. Cayó 100%, muy por encima del 29% que cayó el resto de su subestación. Mientras estuvo activo registraba más energía que el resto de su subestación, así que el corte a cero no cuadra con un local que simplemente dejó de operar. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_004081",
    "sed": "SED_1565",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.563,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 5125.53,
    "score_prioridad": 2884.54,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 5.1 kW contratados. Venía registrando unos 80 kWh al mes y desde junio marca cero: lleva 7 meses seguidos sin registrar consumo. Cayó 100%, muy por encima del 15% que cayó el resto de su subestación. Mientras estuvo activo registraba más energía que el resto de su subestación, así que el corte a cero no cuadra con un local que simplemente dejó de operar. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_002389",
    "sed": "SED_2738",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.563,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 5079.92,
    "score_prioridad": 2861.32,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados. Venía registrando unos 32 kWh al mes y desde junio marca cero: lleva 7 meses seguidos sin registrar consumo. Cayó 100%, muy por encima del 15% que cayó el resto de su subestación. Aun antes de apagarse ya registraba 70% menos que el promedio de su subestación. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_015875",
    "sed": "SED_0539",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.608,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4693.25,
    "score_prioridad": 2854.46,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados y registra un promedio de 46 kWh al mes. Solo registra consumo en 3 de los 12 meses del año. Registra 3 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. Está pagando por 11.1 kW de capacidad pero usa menos del 1% de ella, algo poco habitual en un cliente que mantiene el servicio activo. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_014334",
    "sed": "SED_1538",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.555,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 5141.02,
    "score_prioridad": 2854.16,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados y registra un promedio de 21 kWh al mes. Su consumo cayó 81% entre el inicio y el final del año, sin recuperarse. Cayó 81%, muy por encima del 29% que cayó el resto de su subestación. Registra 60% más energía que el promedio de su subestación. Está pagando por 11.1 kW de capacidad pero usa menos del 1% de ella, algo poco habitual en un cliente que mantiene el servicio activo. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_011528",
    "sed": "SED_1886",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.932,
    "nivel_sospecha": "CRÍTICO",
    "recupero_soles": 3060.95,
    "score_prioridad": 2854.01,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados y registra un promedio de 1,678 kWh al mes. Registra 10 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_004297",
    "sed": "SED_0063",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.546,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 5225.22,
    "score_prioridad": 2853.96,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados. Venía registrando unos 81 kWh al mes y desde octubre marca cero: lleva 3 meses seguidos sin registrar consumo. Cayó 100%, muy por encima del 23% que cayó el resto de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_016262",
    "sed": "SED_1523",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.647,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4411.02,
    "score_prioridad": 2852.47,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados y registra un promedio de 5,519 kWh al mes. Su consumo subió 53% en el año, un salto que no corresponde a variación estacional. Registra 21 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_014878",
    "sed": "SED_2475",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.561,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 5040.25,
    "score_prioridad": 2827.34,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 5.1 kW contratados. Venía registrando unos 52 kWh al mes y desde junio marca cero: lleva 7 meses seguidos sin registrar consumo. Cayó 100%, muy por encima del 9% que cayó el resto de su subestación. Aun antes de apagarse ya registraba 75% menos que el promedio de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_005714",
    "sed": "SED_2738",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.551,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 5098.1,
    "score_prioridad": 2806.94,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados. Venía registrando unos 30 kWh al mes y desde setiembre marca cero: lleva 4 meses seguidos sin registrar consumo. Cayó 100%, muy por encima del 15% que cayó el resto de su subestación. Aun antes de apagarse ya registraba 54% menos que el promedio de su subestación. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_003643",
    "sed": "SED_0515",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.558,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 5001.95,
    "score_prioridad": 2789.48,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados. Venía registrando unos 39 kWh al mes y desde octubre marca cero: lleva 3 meses seguidos sin registrar consumo. Cayó 100%, muy por encima del 24% que cayó el resto de su subestación. Mientras estuvo activo registraba más energía que el resto de su subestación, así que el corte a cero no cuadra con un local que simplemente dejó de operar. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_016085",
    "sed": "SED_2002",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.876,
    "nivel_sospecha": "CRÍTICO",
    "recupero_soles": 3169.3,
    "score_prioridad": 2774.96,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 8.1 kW contratados y registra un promedio de 4,238 kWh al mes. Su consumo cayó 40% entre el inicio y el final del año, sin recuperarse. Cayó 40% mientras el resto de su subestación se mantuvo estable (-2%): la caída es de este suministro, no del sector. Registra 12 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_001518",
    "sed": "SED_0044",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.748,
    "nivel_sospecha": "BAJO",
    "recupero_soles": 3701.17,
    "score_prioridad": 2767.45,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados y registra un promedio de 5,171 kWh al mes. Su consumo subió 156% en el año, un salto que no corresponde a variación estacional. Registra 66 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_013344",
    "sed": "SED_0044",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.781,
    "nivel_sospecha": "MUY ALTO",
    "recupero_soles": 3532.46,
    "score_prioridad": 2759.61,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados y registra un promedio de 2,791 kWh al mes. Su consumo subió 64% en el año, un salto que no corresponde a variación estacional. Registra 35 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_012633",
    "sed": "SED_1207",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.554,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4962.18,
    "score_prioridad": 2750.09,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados y registra un promedio de 26 kWh al mes. Su consumo cayó 76% entre el inicio y el final del año, sin recuperarse. Cayó 76%, muy por encima del 16% que cayó el resto de su subestación. Registra 4 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. Está pagando por 11.1 kW de capacidad pero usa menos del 1% de ella, algo poco habitual en un cliente que mantiene el servicio activo. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_004118",
    "sed": "SED_0670",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.828,
    "nivel_sospecha": "CRÍTICO",
    "recupero_soles": 3322.86,
    "score_prioridad": 2749.86,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados. Venía registrando unos 449 kWh al mes y desde octubre marca cero: lleva 3 meses seguidos sin registrar consumo. Cayó 100%, muy por encima del 29% que cayó el resto de su subestación. Mientras estuvo activo registraba más energía que el resto de su subestación, así que el corte a cero no cuadra con un local que simplemente dejó de operar. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_010398",
    "sed": "SED_2743",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.55,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4987.54,
    "score_prioridad": 2741.54,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 5.1 kW contratados. Venía registrando unos 16 kWh al mes y desde octubre marca cero: lleva 3 meses seguidos sin registrar consumo. Cayó 100%, muy por encima del 35% que cayó el resto de su subestación. Aun antes de apagarse ya registraba 56% menos que el promedio de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_012384",
    "sed": "SED_2329",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.618,
    "nivel_sospecha": "MUY ALTO",
    "recupero_soles": 4409.96,
    "score_prioridad": 2725.36,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados. Venía registrando unos 150 kWh al mes y desde octubre marca cero: lleva 3 meses seguidos sin registrar consumo. Cayó 100%, muy por encima del 34% que cayó el resto de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_006785",
    "sed": "SED_2195",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.75,
    "nivel_sospecha": "MODERADO",
    "recupero_soles": 3627.48,
    "score_prioridad": 2720.3,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 22 kW contratados y registra un promedio de 3,534 kWh al mes. Registra 18 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_002074",
    "sed": "SED_0515",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.588,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4601.6,
    "score_prioridad": 2707.36,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados. Venía registrando unos 186 kWh al mes y desde junio marca cero: lleva 7 meses seguidos sin registrar consumo. Cayó 100%, muy por encima del 14% que cayó el resto de su subestación. Mientras estuvo activo registraba más energía que el resto de su subestación, así que el corte a cero no cuadra con un local que simplemente dejó de operar. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_015688",
    "sed": "SED_2362",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.762,
    "nivel_sospecha": "MUY ALTO",
    "recupero_soles": 3533.89,
    "score_prioridad": 2692.37,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados y registra un promedio de 2,336 kWh al mes. Su consumo subió 164% en el año, un salto que no corresponde a variación estacional. Registra 20 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_006458",
    "sed": "SED_2556",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.549,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4900.35,
    "score_prioridad": 2691.76,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 5.1 kW contratados. Venía registrando unos 31 kWh al mes y desde setiembre marca cero: lleva 4 meses seguidos sin registrar consumo. Cayó 100%, muy por encima del 20% que cayó el resto de su subestación. Aun antes de apagarse ya registraba 69% menos que el promedio de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_013189",
    "sed": "SED_1137",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.593,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4534.91,
    "score_prioridad": 2689.06,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados y registra un promedio de 38 kWh al mes. Su consumo subió 200% en el año, un salto que no corresponde a variación estacional. Registra 22% menos energía que el promedio de los demás suministros de su misma subestación. Está pagando por 11.1 kW de capacidad pero usa menos del 1% de ella, algo poco habitual en un cliente que mantiene el servicio activo. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_010160",
    "sed": "SED_0044",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.745,
    "nivel_sospecha": "BAJO",
    "recupero_soles": 3606.43,
    "score_prioridad": 2687.75,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados y registra un promedio de 4,425 kWh al mes. Registra 57 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_012246",
    "sed": "SED_1206",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.932,
    "nivel_sospecha": "CRÍTICO",
    "recupero_soles": 2878.52,
    "score_prioridad": 2683.96,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12.1 kW contratados y registra un promedio de 1,226 kWh al mes. Su consumo subió 176% en el año, un salto que no corresponde a variación estacional. Registra 11 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_010609",
    "sed": "SED_1538",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.613,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4360.39,
    "score_prioridad": 2672.97,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados y registra un promedio de 37 kWh al mes. Su consumo subió 200% en el año, un salto que no corresponde a variación estacional. Registra 4 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. Está pagando por 11.1 kW de capacidad pero usa menos del 1% de ella, algo poco habitual en un cliente que mantiene el servicio activo. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_000032",
    "sed": "SED_1565",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.549,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4864.33,
    "score_prioridad": 2672.26,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 5.1 kW contratados. Venía registrando unos 26 kWh al mes y desde octubre marca cero: lleva 3 meses seguidos sin registrar consumo. Cayó 100%, muy por encima del 16% que cayó el resto de su subestación. Aun antes de apagarse ya registraba 45% menos que el promedio de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_010946",
    "sed": "SED_2642",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.551,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4849.12,
    "score_prioridad": 2670.83,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados. Venía registrando unos 21 kWh al mes y desde julio marca cero: lleva 6 meses seguidos sin registrar consumo. Cayó 100%, muy por encima del 10% que cayó el resto de su subestación. Aun antes de apagarse ya registraba 77% menos que el promedio de su subestación. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_008803",
    "sed": "SED_2470",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.698,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 3816.96,
    "score_prioridad": 2663.42,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados y registra un promedio de 3,426 kWh al mes. Su consumo subió 69% en el año, un salto que no corresponde a variación estacional. Registra 39 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_018297",
    "sed": "SED_1777",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.898,
    "nivel_sospecha": "CRÍTICO",
    "recupero_soles": 2938.67,
    "score_prioridad": 2639.81,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 3.1 kW contratados y registra un promedio de 1,052 kWh al mes. Su consumo subió 200% en el año, un salto que no corresponde a variación estacional. Registra 10 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_001082",
    "sed": "SED_2105",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.801,
    "nivel_sospecha": "MUY ALTO",
    "recupero_soles": 3291.59,
    "score_prioridad": 2634.93,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 3.1 kW contratados. Venía registrando unos 69 kWh al mes y desde setiembre marca cero: lleva 4 meses seguidos sin registrar consumo. Cayó 100%, muy por encima del 10% que cayó el resto de su subestación. Aun antes de apagarse ya registraba 36% menos que el promedio de su subestación. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_005469",
    "sed": "SED_1523",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.692,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 3791.5,
    "score_prioridad": 2624.75,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 6.1 kW contratados y registra un promedio de 5,611 kWh al mes. Su consumo cayó 57% entre el inicio y el final del año, sin recuperarse. Cayó 57%, muy por encima del 25% que cayó el resto de su subestación. Registra 42 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_018422",
    "sed": "SED_1594",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.626,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4185.16,
    "score_prioridad": 2618.19,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 5.1 kW contratados y registra un promedio de 25 kWh al mes. Su consumo subió 200% en el año, un salto que no corresponde a variación estacional. Está pagando por 5.1 kW de capacidad pero usa menos del 1% de ella, algo poco habitual en un cliente que mantiene el servicio activo. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_011532",
    "sed": "SED_0515",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.554,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4723.78,
    "score_prioridad": 2615.97,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 5.1 kW contratados. Venía registrando unos 35 kWh al mes y desde julio marca cero: lleva 6 meses seguidos sin registrar consumo. Cayó 100%, muy por encima del 14% que cayó el resto de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_010227",
    "sed": "SED_2002",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.747,
    "nivel_sospecha": "MODERADO",
    "recupero_soles": 3494.96,
    "score_prioridad": 2610.68,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados y registra un promedio de 836 kWh al mes. Solo registra consumo en 3 de los 12 meses del año. Registra 13 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_018232",
    "sed": "SED_2413",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.7,
    "nivel_sospecha": "MUY ALTO",
    "recupero_soles": 3724.13,
    "score_prioridad": 2608.19,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados y registra un promedio de 1,097 kWh al mes. Solo registra consumo en 3 de los 12 meses del año. Registra 19 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_010229",
    "sed": "SED_2074",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.549,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4746.31,
    "score_prioridad": 2605.93,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados. Venía registrando unos 20 kWh al mes y desde julio marca cero: lleva 6 meses seguidos sin registrar consumo. Cayó 100%, muy por encima del 8% que cayó el resto de su subestación. Aun antes de apagarse ya registraba 86% menos que el promedio de su subestación. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_000739",
    "sed": "SED_2407",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.561,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4618.45,
    "score_prioridad": 2593.04,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados. Venía registrando unos 48 kWh al mes y desde abril marca cero: lleva 9 meses seguidos sin registrar consumo. Cayó 100%, muy por encima del 14% que cayó el resto de su subestación. Aun antes de apagarse ya registraba 80% menos que el promedio de su subestación. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_003940",
    "sed": "SED_2362",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.648,
    "nivel_sospecha": "MUY ALTO",
    "recupero_soles": 3999.09,
    "score_prioridad": 2590.52,
    "incertidumbre_alta": true,
    "explicacion": "Tiene 5.1 kW contratados y registra un promedio de 80 kWh al mes. Su consumo cayó 54% entre el inicio y el final del año, sin recuperarse. Cayó 54%, muy por encima del 19% que cayó el resto de su subestación. Registra 34% menos energía que el promedio de los demás suministros de su misma subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_001065",
    "sed": "SED_2362",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.689,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 3753.59,
    "score_prioridad": 2585.97,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados y registra un promedio de 3,238 kWh al mes. Registra 28 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_001195",
    "sed": "SED_2642",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.561,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4605.43,
    "score_prioridad": 2583.16,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados. Venía registrando unos 40 kWh al mes y desde mayo marca cero: lleva 8 meses seguidos sin registrar consumo. Cayó 100%, muy por encima del 10% que cayó el resto de su subestación. Aun antes de apagarse ya registraba 70% menos que el promedio de su subestación. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_018799",
    "sed": "SED_0063",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.547,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4695.16,
    "score_prioridad": 2569.64,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados. Venía registrando unos 81 kWh al mes y desde setiembre marca cero: lleva 4 meses seguidos sin registrar consumo. Cayó 100%, muy por encima del 14% que cayó el resto de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_010274",
    "sed": "SED_2789",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.559,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4593.37,
    "score_prioridad": 2569.55,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados. Venía registrando unos 46 kWh al mes y desde abril marca cero: lleva 9 meses seguidos sin registrar consumo. Cayó 100%, muy por encima del 10% que cayó el resto de su subestación. Aun antes de apagarse ya registraba 83% menos que el promedio de su subestación. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_015876",
    "sed": "SED_0853",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.757,
    "nivel_sospecha": "MODERADO",
    "recupero_soles": 3394.39,
    "score_prioridad": 2568.79,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados y registra un promedio de 2,065 kWh al mes. Su consumo subió 44% en el año, un salto que no corresponde a variación estacional. Registra 22 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_006364",
    "sed": "SED_1159",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.611,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4197.78,
    "score_prioridad": 2565.83,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados y registra un promedio de 38 kWh al mes. Su consumo subió 133% en el año, un salto que no corresponde a variación estacional. Registra 16 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. Está pagando por 11.1 kW de capacidad pero usa menos del 1% de ella, algo poco habitual en un cliente que mantiene el servicio activo. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_019587",
    "sed": "SED_0090",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.836,
    "nivel_sospecha": "MUY ALTO",
    "recupero_soles": 3062.31,
    "score_prioridad": 2560.94,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados y registra un promedio de 604 kWh al mes. Solo registra consumo en 3 de los 12 meses del año. Registra 4 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_001764",
    "sed": "SED_0063",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.637,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4005.4,
    "score_prioridad": 2550.15,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 5.1 kW contratados y registra un promedio de 62 kWh al mes. Su consumo subió 200% en el año, un salto que no corresponde a variación estacional. Está pagando por 5.1 kW de capacidad pero usa menos del 1% de ella, algo poco habitual en un cliente que mantiene el servicio activo. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_012663",
    "sed": "SED_2738",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.557,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4574.84,
    "score_prioridad": 2547.88,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados. Venía registrando unos 29 kWh al mes y desde julio marca cero: lleva 6 meses seguidos sin registrar consumo. Cayó 100%, muy por encima del 15% que cayó el resto de su subestación. Aun antes de apagarse ya registraba 66% menos que el promedio de su subestación. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_013290",
    "sed": "SED_2738",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.563,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4526.19,
    "score_prioridad": 2546.38,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados. Venía registrando unos 36 kWh al mes y desde mayo marca cero: lleva 8 meses seguidos sin registrar consumo. Cayó 100%, muy por encima del 15% que cayó el resto de su subestación. Aun antes de apagarse ya registraba 72% menos que el promedio de su subestación. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_006382",
    "sed": "SED_0938",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.852,
    "nivel_sospecha": "MUY ALTO",
    "recupero_soles": 2988.2,
    "score_prioridad": 2544.93,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 8.1 kW contratados y registra un promedio de 405 kWh al mes. Su consumo subió 200% en el año, un salto que no corresponde a variación estacional. Registra 154% más energía que el promedio de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_012607",
    "sed": "SED_1207",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.858,
    "nivel_sospecha": "CRÍTICO",
    "recupero_soles": 2944.68,
    "score_prioridad": 2527.88,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 5.1 kW contratados. Venía registrando unos 138 kWh al mes y desde noviembre marca cero: lleva 2 meses seguidos sin registrar consumo. Cayó 98%, muy por encima del 30% que cayó el resto de su subestación. Mientras estuvo activo registraba más energía que el resto de su subestación, así que el corte a cero no cuadra con un local que simplemente dejó de operar. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_011118",
    "sed": "SED_0498",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.682,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 3704.33,
    "score_prioridad": 2526.23,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados y registra un promedio de 2,671 kWh al mes. Registra 24 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_004253",
    "sed": "SED_0501",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.552,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4563.43,
    "score_prioridad": 2518.4,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 5.1 kW contratados. Venía registrando unos 25 kWh al mes y desde junio marca cero: lleva 7 meses seguidos sin registrar consumo. Cayó 100%, muy por encima del 10% que cayó el resto de su subestación. Aun antes de apagarse ya registraba 89% menos que el promedio de su subestación. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_002164",
    "sed": "SED_0742",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.904,
    "nivel_sospecha": "CRÍTICO",
    "recupero_soles": 2779.58,
    "score_prioridad": 2513.95,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 3.1 kW contratados y registra un promedio de 449 kWh al mes. Su consumo subió 200% en el año, un salto que no corresponde a variación estacional. Registra 3 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_004400",
    "sed": "SED_2295",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.601,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4176.95,
    "score_prioridad": 2511.72,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados. Venía registrando unos 70 kWh al mes y desde noviembre marca cero: lleva 2 meses seguidos sin registrar consumo. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_001643",
    "sed": "SED_2074",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.617,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4069.35,
    "score_prioridad": 2510.78,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados y registra un promedio de 23 kWh al mes. Su consumo subió 200% en el año, un salto que no corresponde a variación estacional. Registra 71% menos energía que el promedio de los demás suministros de su misma subestación. Está pagando por 11.1 kW de capacidad pero usa menos del 1% de ella, algo poco habitual en un cliente que mantiene el servicio activo. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_012733",
    "sed": "SED_2475",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.573,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4375.9,
    "score_prioridad": 2508.91,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 3.1 kW contratados. Venía registrando unos 55 kWh al mes y desde mayo marca cero: lleva 8 meses seguidos sin registrar consumo. Cayó 100%, muy por encima del 9% que cayó el resto de su subestación. Aun antes de apagarse ya registraba 74% menos que el promedio de su subestación. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_000996",
    "sed": "SED_1159",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.578,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4337.86,
    "score_prioridad": 2506.94,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados. Venía registrando unos 59 kWh al mes y desde noviembre marca cero: lleva 2 meses seguidos sin registrar consumo. Mientras estuvo activo registraba más energía que el resto de su subestación, así que el corte a cero no cuadra con un local que simplemente dejó de operar. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_003806",
    "sed": "SED_2475",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.912,
    "nivel_sospecha": "CRÍTICO",
    "recupero_soles": 2742.35,
    "score_prioridad": 2500.05,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 3.1 kW contratados y registra un promedio de 260 kWh al mes. Su consumo subió 200% en el año, un salto que no corresponde a variación estacional. Registra 4 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_013768",
    "sed": "SED_2363",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.557,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4456.55,
    "score_prioridad": 2482.11,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados. Venía registrando unos 18 kWh al mes y desde octubre marca cero: lleva 3 meses seguidos sin registrar consumo. Cayó 100%, muy por encima del 13% que cayó el resto de su subestación. Aun antes de apagarse ya registraba 61% menos que el promedio de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  }
];
