import { Suministro, ResumenAlimentador } from "./types";

export const CORTE_CRITICA = 100;

export const resumenAlimentador: ResumenAlimentador = {
  "alimentador": "ALIM_311",
  "suministros": 14951,
  "transformadores": 95,
  "zonas": 29,
  "llaves": 7,
  "tarifa": "BT5 B",
  "inspeccionar": 100,
  "transformadores_con_alerta": 48,
  "recupero_soles": 456167.4968336011
};

export const mockData: Suministro[] = [
  {
    "suministro": "SUM_009931",
    "sed": "SED_0515",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.553,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 7924.82,
    "score_prioridad": 4384.12,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados. Venía registrando unos 20 kWh al mes y desde setiembre marca cero: lleva 4 meses seguidos sin registrar consumo. Aun antes de apagarse ya registraba 24% menos que el promedio de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_004030",
    "sed": "SED_1137",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.532,
    "nivel_sospecha": "MODERADO",
    "recupero_soles": 8194.21,
    "score_prioridad": 4359.86,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados. Venía registrando unos 38 kWh al mes y desde noviembre marca cero: lleva 2 meses seguidos sin registrar consumo. Aun antes de apagarse ya registraba 28% menos que el promedio de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_009955",
    "sed": "SED_1207",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.558,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 7632.81,
    "score_prioridad": 4257.08,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados. Venía registrando unos 54 kWh al mes y desde octubre marca cero: lleva 3 meses seguidos sin registrar consumo. Mientras estuvo activo registraba más energía que el resto de su subestación, así que el corte a cero no cuadra con un local que simplemente dejó de operar. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_017526",
    "sed": "SED_1482",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.611,
    "nivel_sospecha": "MODERADO",
    "recupero_soles": 6781.83,
    "score_prioridad": 4140.6,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados y registra un promedio de 25 kWh al mes. Su consumo cayó 63% entre el inicio y el final del año, sin recuperarse. Registra 16% menos energía que el promedio de los demás suministros de su misma subestación. Está pagando por 11.1 kW de capacidad pero usa menos del 1% de ella, algo poco habitual en un cliente que mantiene el servicio activo. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_011487",
    "sed": "SED_0515",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.553,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 7184.52,
    "score_prioridad": 3975.55,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados. Venía registrando unos 18 kWh al mes y desde setiembre marca cero: lleva 4 meses seguidos sin registrar consumo. Aun antes de apagarse ya registraba 40% menos que el promedio de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_006162",
    "sed": "SED_1019",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.539,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 7194.43,
    "score_prioridad": 3879.58,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados. Venía registrando unos 31 kWh al mes y desde noviembre marca cero: lleva 2 meses seguidos sin registrar consumo. Aun antes de apagarse ya registraba 47% menos que el promedio de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_011528",
    "sed": "SED_1886",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.932,
    "nivel_sospecha": "CRÍTICO",
    "recupero_soles": 4069.45,
    "score_prioridad": 3794.32,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados y registra un promedio de 1,678 kWh al mes. Registra 10 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_002297",
    "sed": "SED_0974",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.942,
    "nivel_sospecha": "CRÍTICO",
    "recupero_soles": 4019.75,
    "score_prioridad": 3784.88,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados y registra un promedio de 2,454 kWh al mes. Su consumo subió 108% en el año, un salto que no corresponde a variación estacional. Registra 18 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_007851",
    "sed": "SED_1538",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.916,
    "nivel_sospecha": "CRÍTICO",
    "recupero_soles": 4082.64,
    "score_prioridad": 3737.69,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados y registra un promedio de 5,239 kWh al mes. Su consumo cayó 96% entre el inicio y el final del año, sin recuperarse. Registra 551 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_016339",
    "sed": "SED_2661",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.907,
    "nivel_sospecha": "CRÍTICO",
    "recupero_soles": 4109.33,
    "score_prioridad": 3728.55,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados y registra un promedio de 4,680 kWh al mes. Su consumo cayó 45% entre el inicio y el final del año, sin recuperarse. Registra 33 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_006050",
    "sed": "SED_0090",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.547,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 6666.69,
    "score_prioridad": 3649.51,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12.1 kW contratados. Venía registrando unos 16 kWh al mes y desde octubre marca cero: lleva 3 meses seguidos sin registrar consumo. Aun antes de apagarse ya registraba 90% menos que el promedio de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_014910",
    "sed": "SED_1207",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.573,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 6345.57,
    "score_prioridad": 3636.96,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 5.1 kW contratados. Venía registrando unos 19 kWh al mes y desde noviembre marca cero: lleva 2 meses seguidos sin registrar consumo. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_005714",
    "sed": "SED_2738",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.551,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 6473.71,
    "score_prioridad": 3564.33,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados. Venía registrando unos 30 kWh al mes y desde setiembre marca cero: lleva 4 meses seguidos sin registrar consumo. Aun antes de apagarse ya registraba 54% menos que el promedio de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_000944",
    "sed": "SED_1942",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.897,
    "nivel_sospecha": "CRÍTICO",
    "recupero_soles": 3972.19,
    "score_prioridad": 3561.41,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados y registra un promedio de 1,968 kWh al mes. Registra 11 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_001565",
    "sed": "SED_1538",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.583,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 5940.25,
    "score_prioridad": 3461.46,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 5.1 kW contratados. Venía registrando unos 29 kWh al mes y desde junio marca cero: lleva 7 meses seguidos sin registrar consumo. Mientras estuvo activo registraba más energía que el resto de su subestación, así que el corte a cero no cuadra con un local que simplemente dejó de operar. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_000475",
    "sed": "SED_2362",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.874,
    "nivel_sospecha": "CRÍTICO",
    "recupero_soles": 3870.37,
    "score_prioridad": 3381.11,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados. Venía registrando unos 1,165 kWh al mes y desde octubre marca cero: lleva 3 meses seguidos sin registrar consumo. Mientras estuvo activo registraba más energía que el resto de su subestación, así que el corte a cero no cuadra con un local que simplemente dejó de operar. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_004099",
    "sed": "SED_2195",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.936,
    "nivel_sospecha": "CRÍTICO",
    "recupero_soles": 3591.74,
    "score_prioridad": 3361.66,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados y registra un promedio de 2,837 kWh al mes. Su consumo subió 129% en el año, un salto que no corresponde a variación estacional. Registra 12 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_005907",
    "sed": "SED_2475",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.795,
    "nivel_sospecha": "MUY ALTO",
    "recupero_soles": 4226.51,
    "score_prioridad": 3358.65,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados y registra un promedio de 3,845 kWh al mes. Su consumo subió 76% en el año, un salto que no corresponde a variación estacional. Registra 53 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_013056",
    "sed": "SED_2475",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.616,
    "nivel_sospecha": "MUY ALTO",
    "recupero_soles": 5323.19,
    "score_prioridad": 3278.97,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 3.1 kW contratados. Venía registrando unos 46 kWh al mes y desde noviembre marca cero: lleva 2 meses seguidos sin registrar consumo. Aun antes de apagarse ya registraba 31% menos que el promedio de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_008448",
    "sed": "SED_0933",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.946,
    "nivel_sospecha": "CRÍTICO",
    "recupero_soles": 3452.58,
    "score_prioridad": 3264.59,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados y registra un promedio de 2,966 kWh al mes. Su consumo subió 71% en el año, un salto que no corresponde a variación estacional. Registra 27 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_008563",
    "sed": "SED_0515",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.574,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 5653.66,
    "score_prioridad": 3246.7,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados. Venía registrando unos 57 kWh al mes y desde octubre marca cero: lleva 3 meses seguidos sin registrar consumo. Mientras estuvo activo registraba más energía que el resto de su subestación, así que el corte a cero no cuadra con un local que simplemente dejó de operar. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_006458",
    "sed": "SED_2556",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.549,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 5852.39,
    "score_prioridad": 3214.72,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 5.1 kW contratados. Venía registrando unos 31 kWh al mes y desde setiembre marca cero: lleva 4 meses seguidos sin registrar consumo. Aun antes de apagarse ya registraba 69% menos que el promedio de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_005743",
    "sed": "SED_1207",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.547,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 5854.02,
    "score_prioridad": 3204.27,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados. Venía registrando unos 14 kWh al mes y desde octubre marca cero: lleva 3 meses seguidos sin registrar consumo. Aun antes de apagarse ya registraba 37% menos que el promedio de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_012471",
    "sed": "SED_0515",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.551,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 5759.55,
    "score_prioridad": 3172.33,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados y registra un promedio de 19 kWh al mes. Su consumo cayó 82% entre el inicio y el final del año, sin recuperarse. Está pagando por 11.1 kW de capacidad pero usa menos del 1% de ella, algo poco habitual en un cliente que mantiene el servicio activo. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_001109",
    "sed": "SED_2413",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.941,
    "nivel_sospecha": "CRÍTICO",
    "recupero_soles": 3361.41,
    "score_prioridad": 3163.18,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados y registra un promedio de 1,592 kWh al mes. Su consumo subió 200% en el año, un salto que no corresponde a variación estacional. Registra 29 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_010217",
    "sed": "SED_1538",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.545,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 5777.96,
    "score_prioridad": 3149.04,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados y registra un promedio de 22 kWh al mes. Registra 3 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. Está pagando por 11.1 kW de capacidad pero usa menos del 1% de ella, algo poco habitual en un cliente que mantiene el servicio activo. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_011741",
    "sed": "SED_0035",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.897,
    "nivel_sospecha": "CRÍTICO",
    "recupero_soles": 3481.9,
    "score_prioridad": 3122.61,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados. Venía registrando unos 1,818 kWh al mes y desde octubre marca cero: lleva 3 meses seguidos sin registrar consumo. Mientras estuvo activo registraba más energía que el resto de su subestación, así que el corte a cero no cuadra con un local que simplemente dejó de operar. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_018799",
    "sed": "SED_0063",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.547,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 5681.28,
    "score_prioridad": 3109.34,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados. Venía registrando unos 81 kWh al mes y desde setiembre marca cero: lleva 4 meses seguidos sin registrar consumo. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_000990",
    "sed": "SED_1041",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.941,
    "nivel_sospecha": "CRÍTICO",
    "recupero_soles": 3292.63,
    "score_prioridad": 3098.78,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados y registra un promedio de 2,344 kWh al mes. Registra 31 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_005240",
    "sed": "SED_1019",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.676,
    "nivel_sospecha": "MUY ALTO",
    "recupero_soles": 4546.89,
    "score_prioridad": 3073.72,
    "incertidumbre_alta": true,
    "explicacion": "Tiene 5.1 kW contratados. Venía registrando unos 80 kWh al mes y desde noviembre marca cero: lleva 2 meses seguidos sin registrar consumo. Mientras estuvo activo registraba más energía que el resto de su subestación, así que el corte a cero no cuadra con un local que simplemente dejó de operar. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_001082",
    "sed": "SED_2105",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.801,
    "nivel_sospecha": "MUY ALTO",
    "recupero_soles": 3811.34,
    "score_prioridad": 3051.0,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 3.1 kW contratados. Venía registrando unos 69 kWh al mes y desde setiembre marca cero: lleva 4 meses seguidos sin registrar consumo. Aun antes de apagarse ya registraba 36% menos que el promedio de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_016429",
    "sed": "SED_1159",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.566,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 5376.8,
    "score_prioridad": 3043.8,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados y registra un promedio de 24 kWh al mes. Su consumo cayó 82% entre el inicio y el final del año, sin recuperarse. Registra 3 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. Está pagando por 11.1 kW de capacidad pero usa menos del 1% de ella, algo poco habitual en un cliente que mantiene el servicio activo. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_016085",
    "sed": "SED_2002",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.876,
    "nivel_sospecha": "CRÍTICO",
    "recupero_soles": 3440.48,
    "score_prioridad": 3012.4,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 8.1 kW contratados y registra un promedio de 4,238 kWh al mes. Su consumo cayó 40% entre el inicio y el final del año, sin recuperarse. Registra 12 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_001518",
    "sed": "SED_0044",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.748,
    "nivel_sospecha": "BAJO",
    "recupero_soles": 3977.83,
    "score_prioridad": 2974.32,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados y registra un promedio de 5,171 kWh al mes. Su consumo subió 156% en el año, un salto que no corresponde a variación estacional. Registra 66 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_017009",
    "sed": "SED_0837",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.781,
    "nivel_sospecha": "MUY ALTO",
    "recupero_soles": 3779.25,
    "score_prioridad": 2950.41,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 3.1 kW contratados. Venía registrando unos 119 kWh al mes y desde setiembre marca cero: lleva 4 meses seguidos sin registrar consumo. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_016262",
    "sed": "SED_1523",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.647,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4552.58,
    "score_prioridad": 2944.01,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados y registra un promedio de 5,519 kWh al mes. Su consumo subió 53% en el año, un salto que no corresponde a variación estacional. Registra 21 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_015909",
    "sed": "SED_2738",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.544,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 5366.03,
    "score_prioridad": 2917.76,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados. Venía registrando unos 66 kWh al mes y desde octubre marca cero: lleva 3 meses seguidos sin registrar consumo. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_005952",
    "sed": "SED_2475",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.559,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 5175.31,
    "score_prioridad": 2895.09,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 3.1 kW contratados. Venía registrando unos 27 kWh al mes y desde octubre marca cero: lleva 3 meses seguidos sin registrar consumo. Aun antes de apagarse ya registraba 63% menos que el promedio de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_016528",
    "sed": "SED_0515",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.595,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4827.55,
    "score_prioridad": 2874.31,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados y registra un promedio de 22 kWh al mes. Su consumo subió 200% en el año, un salto que no corresponde a variación estacional. Registra 30% menos energía que el promedio de los demás suministros de su misma subestación. Está pagando por 11.1 kW de capacidad pero usa menos del 1% de ella, algo poco habitual en un cliente que mantiene el servicio activo. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_003643",
    "sed": "SED_0515",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.558,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 5112.42,
    "score_prioridad": 2851.09,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados. Venía registrando unos 39 kWh al mes y desde octubre marca cero: lleva 3 meses seguidos sin registrar consumo. Mientras estuvo activo registraba más energía que el resto de su subestación, así que el corte a cero no cuadra con un local que simplemente dejó de operar. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_003931",
    "sed": "SED_2181",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.633,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4498.64,
    "score_prioridad": 2845.71,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados y registra un promedio de 16 kWh al mes. Su consumo subió 200% en el año, un salto que no corresponde a variación estacional. Registra 333 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. Está pagando por 11.1 kW de capacidad pero usa menos del 1% de ella, algo poco habitual en un cliente que mantiene el servicio activo. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_007710",
    "sed": "SED_1041",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.933,
    "nivel_sospecha": "CRÍTICO",
    "recupero_soles": 3043.2,
    "score_prioridad": 2840.33,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados y registra un promedio de 1,561 kWh al mes. Solo registra consumo en 5 de los 12 meses del año. Registra 17 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_010889",
    "sed": "SED_1538",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.605,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4668.28,
    "score_prioridad": 2823.52,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados y registra un promedio de 19 kWh al mes. Su consumo subió 200% en el año, un salto que no corresponde a variación estacional. Registra 2 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. Está pagando por 11.1 kW de capacidad pero usa menos del 1% de ella, algo poco habitual en un cliente que mantiene el servicio activo. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_010946",
    "sed": "SED_2642",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.551,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 5103.73,
    "score_prioridad": 2811.07,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados. Venía registrando unos 21 kWh al mes y desde julio marca cero: lleva 6 meses seguidos sin registrar consumo. Aun antes de apagarse ya registraba 77% menos que el promedio de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_000996",
    "sed": "SED_1159",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.578,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4831.67,
    "score_prioridad": 2792.32,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados. Venía registrando unos 59 kWh al mes y desde noviembre marca cero: lleva 2 meses seguidos sin registrar consumo. Mientras estuvo activo registraba más energía que el resto de su subestación, así que el corte a cero no cuadra con un local que simplemente dejó de operar. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_013336",
    "sed": "SED_1538",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.563,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4935.72,
    "score_prioridad": 2777.81,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados. Venía registrando unos 38 kWh al mes y desde octubre marca cero: lleva 3 meses seguidos sin registrar consumo. Mientras estuvo activo registraba más energía que el resto de su subestación, así que el corte a cero no cuadra con un local que simplemente dejó de operar. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_004297",
    "sed": "SED_0063",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.546,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 5067.27,
    "score_prioridad": 2767.69,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados. Venía registrando unos 81 kWh al mes y desde octubre marca cero: lleva 3 meses seguidos sin registrar consumo. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_017150",
    "sed": "SED_1270",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.939,
    "nivel_sospecha": "CRÍTICO",
    "recupero_soles": 2944.09,
    "score_prioridad": 2764.81,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados y registra un promedio de 2,228 kWh al mes. Su consumo subió 200% en el año, un salto que no corresponde a variación estacional. Registra 20 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_002580",
    "sed": "SED_0515",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.575,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4810.01,
    "score_prioridad": 2763.42,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados. Venía registrando unos 68 kWh al mes y desde junio marca cero: lleva 7 meses seguidos sin registrar consumo. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_018341",
    "sed": "SED_0515",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.584,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4688.62,
    "score_prioridad": 2738.12,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados y registra un promedio de 22 kWh al mes. Solo registra consumo en 9 de los 12 meses del año. Está pagando por 12 kW de capacidad pero usa menos del 1% de ella, algo poco habitual en un cliente que mantiene el servicio activo. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_002895",
    "sed": "SED_0212",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.554,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4909.67,
    "score_prioridad": 2721.39,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados. Venía registrando unos 49 kWh al mes y desde octubre marca cero: lleva 3 meses seguidos sin registrar consumo. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_010398",
    "sed": "SED_2743",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.55,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4935.29,
    "score_prioridad": 2712.81,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 5.1 kW contratados. Venía registrando unos 16 kWh al mes y desde octubre marca cero: lleva 3 meses seguidos sin registrar consumo. Aun antes de apagarse ya registraba 56% menos que el promedio de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_009486",
    "sed": "SED_2295",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.845,
    "nivel_sospecha": "CRÍTICO",
    "recupero_soles": 3182.81,
    "score_prioridad": 2690.83,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados. Venía registrando unos 416 kWh al mes y desde noviembre marca cero: lleva 2 meses seguidos sin registrar consumo. Mientras estuvo activo registraba más energía que el resto de su subestación, así que el corte a cero no cuadra con un local que simplemente dejó de operar. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_009540",
    "sed": "SED_0938",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.651,
    "nivel_sospecha": "MUY ALTO",
    "recupero_soles": 4131.77,
    "score_prioridad": 2690.08,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados. Venía registrando unos 171 kWh al mes y desde setiembre marca cero: lleva 4 meses seguidos sin registrar consumo. Aun antes de apagarse ya registraba 29% menos que el promedio de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_003889",
    "sed": "SED_0515",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.6,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4478.71,
    "score_prioridad": 2689.36,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados y registra un promedio de 10 kWh al mes. Su consumo subió 200% en el año, un salto que no corresponde a variación estacional. Registra 35% menos energía que el promedio de los demás suministros de su misma subestación. Está pagando por 11.1 kW de capacidad pero usa menos del 1% de ella, algo poco habitual en un cliente que mantiene el servicio activo. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_010160",
    "sed": "SED_0044",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.745,
    "nivel_sospecha": "BAJO",
    "recupero_soles": 3599.87,
    "score_prioridad": 2682.86,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados y registra un promedio de 4,425 kWh al mes. Registra 57 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_010229",
    "sed": "SED_2074",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.549,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4876.26,
    "score_prioridad": 2677.28,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados. Venía registrando unos 20 kWh al mes y desde julio marca cero: lleva 6 meses seguidos sin registrar consumo. Aun antes de apagarse ya registraba 86% menos que el promedio de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_018516",
    "sed": "SED_1159",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.57,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4692.77,
    "score_prioridad": 2674.42,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados y registra un promedio de 39 kWh al mes. Su consumo cayó 84% entre el inicio y el final del año, sin recuperarse. Registra 5 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. Está pagando por 11.1 kW de capacidad pero usa menos del 1% de ella, algo poco habitual en un cliente que mantiene el servicio activo. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_013344",
    "sed": "SED_0044",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.781,
    "nivel_sospecha": "MUY ALTO",
    "recupero_soles": 3409.65,
    "score_prioridad": 2663.67,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados y registra un promedio de 2,791 kWh al mes. Su consumo subió 64% en el año, un salto que no corresponde a variación estacional. Registra 35 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_001336",
    "sed": "SED_0151",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.651,
    "nivel_sospecha": "MUY ALTO",
    "recupero_soles": 4067.98,
    "score_prioridad": 2646.73,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 5.1 kW contratados. Venía registrando unos 78 kWh al mes y desde setiembre marca cero: lleva 4 meses seguidos sin registrar consumo. Aun antes de apagarse ya registraba 41% menos que el promedio de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_012079",
    "sed": "SED_1019",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.54,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4890.89,
    "score_prioridad": 2640.2,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados y registra un promedio de 36 kWh al mes. Su consumo cayó 69% entre el inicio y el final del año, sin recuperarse. Registra 29% menos energía que el promedio de los demás suministros de su misma subestación. Está pagando por 12 kW de capacidad pero usa menos del 1% de ella, algo poco habitual en un cliente que mantiene el servicio activo. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_011954",
    "sed": "SED_0933",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.568,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4648.61,
    "score_prioridad": 2639.05,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados. Venía registrando unos 326 kWh al mes y desde setiembre marca cero: lleva 4 meses seguidos sin registrar consumo. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_006848",
    "sed": "SED_0061",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.793,
    "nivel_sospecha": "MUY ALTO",
    "recupero_soles": 3309.3,
    "score_prioridad": 2624.27,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 5.1 kW contratados. Venía registrando unos 178 kWh al mes y desde agosto marca cero: lleva 5 meses seguidos sin registrar consumo. Mientras estuvo activo registraba más energía que el resto de su subestación, así que el corte a cero no cuadra con un local que simplemente dejó de operar. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_018439",
    "sed": "SED_2738",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.543,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4783.77,
    "score_prioridad": 2599.46,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados. Venía registrando unos 70 kWh al mes y desde noviembre marca cero: lleva 2 meses seguidos sin registrar consumo. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_002389",
    "sed": "SED_2738",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.563,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4599.3,
    "score_prioridad": 2590.61,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados. Venía registrando unos 32 kWh al mes y desde junio marca cero: lleva 7 meses seguidos sin registrar consumo. Aun antes de apagarse ya registraba 70% menos que el promedio de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_009490",
    "sed": "SED_1538",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.567,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4569.34,
    "score_prioridad": 2590.09,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados y registra un promedio de 22 kWh al mes. Su consumo cayó 95% entre el inicio y el final del año, sin recuperarse. Está pagando por 11.1 kW de capacidad pero usa menos del 1% de ella, algo poco habitual en un cliente que mantiene el servicio activo. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_014340",
    "sed": "SED_2362",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.751,
    "nivel_sospecha": "MUY ALTO",
    "recupero_soles": 3443.64,
    "score_prioridad": 2587.56,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados y registra un promedio de 6,393 kWh al mes. Registra 55 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_012731",
    "sed": "SED_2181",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.643,
    "nivel_sospecha": "MODERADO",
    "recupero_soles": 4009.11,
    "score_prioridad": 2576.67,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados y registra un promedio de 18 kWh al mes. Su consumo subió 193% en el año, un salto que no corresponde a variación estacional. Registra 372 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. Está pagando por 11.1 kW de capacidad pero usa menos del 1% de ella, algo poco habitual en un cliente que mantiene el servicio activo. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_013987",
    "sed": "SED_2738",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.547,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4693.05,
    "score_prioridad": 2566.51,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados. Venía registrando unos 34 kWh al mes y desde julio marca cero: lleva 6 meses seguidos sin registrar consumo. Aun antes de apagarse ya registraba 61% menos que el promedio de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_011118",
    "sed": "SED_0498",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.682,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 3757.36,
    "score_prioridad": 2562.4,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados y registra un promedio de 2,671 kWh al mes. Registra 24 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_018243",
    "sed": "SED_1207",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.604,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4240.99,
    "score_prioridad": 2559.54,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados. Venía registrando unos 58 kWh al mes y desde setiembre marca cero: lleva 4 meses seguidos sin registrar consumo. Mientras estuvo activo registraba más energía que el resto de su subestación, así que el corte a cero no cuadra con un local que simplemente dejó de operar. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_013475",
    "sed": "SED_0061",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.562,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4554.67,
    "score_prioridad": 2559.31,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados. Venía registrando unos 29 kWh al mes y desde agosto marca cero: lleva 5 meses seguidos sin registrar consumo. Aun antes de apagarse ya registraba 62% menos que el promedio de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_003734",
    "sed": "SED_0670",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.568,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4507.23,
    "score_prioridad": 2559.06,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 3.1 kW contratados. Venía registrando unos 22 kWh al mes y desde agosto marca cero: lleva 5 meses seguidos sin registrar consumo. Aun antes de apagarse ya registraba 86% menos que el promedio de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_011532",
    "sed": "SED_0515",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.554,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4581.6,
    "score_prioridad": 2537.24,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 5.1 kW contratados. Venía registrando unos 35 kWh al mes y desde julio marca cero: lleva 6 meses seguidos sin registrar consumo. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_004744",
    "sed": "SED_2295",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.553,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4551.55,
    "score_prioridad": 2517.25,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados. Venía registrando unos 17 kWh al mes y desde octubre marca cero: lleva 3 meses seguidos sin registrar consumo. Aun antes de apagarse ya registraba 70% menos que el promedio de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_014334",
    "sed": "SED_1538",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.555,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4531.32,
    "score_prioridad": 2515.66,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados y registra un promedio de 21 kWh al mes. Su consumo cayó 81% entre el inicio y el final del año, sin recuperarse. Registra 60% más energía que el promedio de su subestación. Está pagando por 11.1 kW de capacidad pero usa menos del 1% de ella, algo poco habitual en un cliente que mantiene el servicio activo. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_004082",
    "sed": "SED_1538",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.611,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4115.94,
    "score_prioridad": 2514.46,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 5.1 kW contratados y registra un promedio de 24 kWh al mes. Su consumo subió 200% en el año, un salto que no corresponde a variación estacional. Registra 4 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. Está pagando por 5.1 kW de capacidad pero usa menos del 1% de ella, algo poco habitual en un cliente que mantiene el servicio activo. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_013768",
    "sed": "SED_2363",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.557,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4494.78,
    "score_prioridad": 2503.41,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados. Venía registrando unos 18 kWh al mes y desde octubre marca cero: lleva 3 meses seguidos sin registrar consumo. Aun antes de apagarse ya registraba 61% menos que el promedio de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_010536",
    "sed": "SED_1207",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.603,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4127.92,
    "score_prioridad": 2489.21,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados y registra un promedio de 27 kWh al mes. Su consumo subió 200% en el año, un salto que no corresponde a variación estacional. Registra 4 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. Está pagando por 12 kW de capacidad pero usa menos del 1% de ella, algo poco habitual en un cliente que mantiene el servicio activo. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_006641",
    "sed": "SED_1019",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.549,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4530.68,
    "score_prioridad": 2487.93,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados. Venía registrando unos 38 kWh al mes y desde octubre marca cero: lleva 3 meses seguidos sin registrar consumo. Aun antes de apagarse ya registraba 45% menos que el promedio de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_000731",
    "sed": "SED_2181",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.593,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4188.64,
    "score_prioridad": 2484.6,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados y registra un promedio de 20 kWh al mes. Su consumo cayó 97% entre el inicio y el final del año, sin recuperarse. Registra 250 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. Está pagando por 12 kW de capacidad pero usa menos del 1% de ella, algo poco habitual en un cliente que mantiene el servicio activo. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_016916",
    "sed": "SED_2475",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.555,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4471.42,
    "score_prioridad": 2480.87,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 3.1 kW contratados. Venía registrando unos 39 kWh al mes y desde setiembre marca cero: lleva 4 meses seguidos sin registrar consumo. Aun antes de apagarse ya registraba 58% menos que el promedio de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_012633",
    "sed": "SED_1207",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.554,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4473.2,
    "score_prioridad": 2479.09,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados y registra un promedio de 26 kWh al mes. Su consumo cayó 76% entre el inicio y el final del año, sin recuperarse. Registra 4 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. Está pagando por 11.1 kW de capacidad pero usa menos del 1% de ella, algo poco habitual en un cliente que mantiene el servicio activo. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_011374",
    "sed": "SED_1041",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.585,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4236.07,
    "score_prioridad": 2477.62,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados. Venía registrando unos 41 kWh al mes y desde agosto marca cero: lleva 5 meses seguidos sin registrar consumo. Aun antes de apagarse ya registraba 68% menos que el promedio de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_012607",
    "sed": "SED_1207",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.858,
    "nivel_sospecha": "CRÍTICO",
    "recupero_soles": 2886.1,
    "score_prioridad": 2477.6,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 5.1 kW contratados. Venía registrando unos 138 kWh al mes y desde noviembre marca cero: lleva 2 meses seguidos sin registrar consumo. Mientras estuvo activo registraba más energía que el resto de su subestación, así que el corte a cero no cuadra con un local que simplemente dejó de operar. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_018545",
    "sed": "SED_0450",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.549,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4480.77,
    "score_prioridad": 2461.34,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados. Venía registrando unos 49 kWh al mes y desde octubre marca cero: lleva 3 meses seguidos sin registrar consumo. Aun antes de apagarse ya registraba 66% menos que el promedio de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_000317",
    "sed": "SED_2789",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.651,
    "nivel_sospecha": "MUY ALTO",
    "recupero_soles": 3778.33,
    "score_prioridad": 2461.07,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 5.1 kW contratados. Venía registrando unos 65 kWh al mes y desde octubre marca cero: lleva 3 meses seguidos sin registrar consumo. Aun antes de apagarse ya registraba 30% menos que el promedio de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_004253",
    "sed": "SED_0501",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.552,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4456.8,
    "score_prioridad": 2459.56,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 5.1 kW contratados. Venía registrando unos 25 kWh al mes y desde junio marca cero: lleva 7 meses seguidos sin registrar consumo. Aun antes de apagarse ya registraba 89% menos que el promedio de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_003499",
    "sed": "SED_0515",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.603,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4069.52,
    "score_prioridad": 2453.41,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados y registra un promedio de 24 kWh al mes. Su consumo subió 200% en el año, un salto que no corresponde a variación estacional. Registra 62% más energía que el promedio de su subestación. Está pagando por 11.1 kW de capacidad pero usa menos del 1% de ella, algo poco habitual en un cliente que mantiene el servicio activo. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_015411",
    "sed": "SED_2181",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.634,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 3867.35,
    "score_prioridad": 2453.29,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 11.1 kW contratados y registra un promedio de 19 kWh al mes. Su consumo subió 200% en el año, un salto que no corresponde a variación estacional. Registra 329 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. Está pagando por 11.1 kW de capacidad pero usa menos del 1% de ella, algo poco habitual en un cliente que mantiene el servicio activo. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_005469",
    "sed": "SED_1523",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.692,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 3537.09,
    "score_prioridad": 2448.63,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 6.1 kW contratados y registra un promedio de 5,611 kWh al mes. Su consumo cayó 57% entre el inicio y el final del año, sin recuperarse. Registra 42 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_003296",
    "sed": "SED_0035",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.842,
    "nivel_sospecha": "CRÍTICO",
    "recupero_soles": 2908.56,
    "score_prioridad": 2448.42,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados y registra un promedio de 276 kWh al mes. Su consumo cayó 83% entre el inicio y el final del año, sin recuperarse. Registra 6 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_012246",
    "sed": "SED_1206",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.932,
    "nivel_sospecha": "CRÍTICO",
    "recupero_soles": 2625.51,
    "score_prioridad": 2448.05,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12.1 kW contratados y registra un promedio de 1,226 kWh al mes. Su consumo subió 176% en el año, un salto que no corresponde a variación estacional. Registra 11 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_008803",
    "sed": "SED_2470",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.698,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 3505.16,
    "score_prioridad": 2445.85,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados y registra un promedio de 3,426 kWh al mes. Su consumo subió 69% en el año, un salto que no corresponde a variación estacional. Registra 39 veces más energía que el promedio de su subestación, con lecturas muy irregulares mes a mes. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_006630",
    "sed": "SED_0038",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.566,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4313.69,
    "score_prioridad": 2439.64,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados. Venía registrando unos 291 kWh al mes y desde junio marca cero: lleva 7 meses seguidos sin registrar consumo. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_013623",
    "sed": "SED_1137",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.55,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4425.37,
    "score_prioridad": 2433.17,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 12 kW contratados. Venía registrando unos 50 kWh al mes y desde noviembre marca cero: lleva 2 meses seguidos sin registrar consumo. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_009770",
    "sed": "SED_1594",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.556,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4369.94,
    "score_prioridad": 2430.3,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 5.1 kW contratados. Venía registrando unos 38 kWh al mes y desde mayo marca cero: lleva 8 meses seguidos sin registrar consumo. Aun antes de apagarse ya registraba 54% menos que el promedio de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  },
  {
    "suministro": "SUM_013698",
    "sed": "SED_2329",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.801,
    "nivel_sospecha": "CRÍTICO",
    "recupero_soles": 3033.0,
    "score_prioridad": 2428.89,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 3.1 kW contratados. Venía registrando unos 109 kWh al mes y desde noviembre marca cero: lleva 2 meses seguidos sin registrar consumo. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_013499",
    "sed": "SED_0090",
    "tipo": "MANIPULACIÓN",
    "probabilidad": 0.889,
    "nivel_sospecha": "CRÍTICO",
    "recupero_soles": 2725.12,
    "score_prioridad": 2423.09,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 8.1 kW contratados. Venía registrando unos 1,280 kWh al mes y desde octubre marca cero: lleva 3 meses seguidos sin registrar consumo. Mientras estuvo activo registraba más energía que el resto de su subestación, así que el corte a cero no cuadra con un local que simplemente dejó de operar. El patrón es compatible con una alteración del medidor: revisar sellos, borneras y contrastar la precisión del equipo."
  },
  {
    "suministro": "SUM_002211",
    "sed": "SED_2661",
    "tipo": "CLANDESTINA",
    "probabilidad": 0.567,
    "nivel_sospecha": "ALTO",
    "recupero_soles": 4260.93,
    "score_prioridad": 2417.53,
    "incertidumbre_alta": false,
    "explicacion": "Tiene 5.1 kW contratados. Venía registrando unos 87 kWh al mes y desde agosto marca cero: lleva 5 meses seguidos sin registrar consumo. Aun antes de apagarse ya registraba 20% menos que el promedio de su subestación. El patrón es compatible con una conexión directa a la red: conviene rastrear el cable de acometida desde el poste antes de abrir la caja del medidor."
  }
];
